//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simon8029.EMPDemo.Model
{
	public partial class EM_Campaigns
	{
		public EM_Campaigns ToPOCO(){
			return new EM_Campaigns(){
				CampaignID=this.CampaignID,
				StartDate=this.StartDate,
				EndDate=this.EndDate,
				CampaignName=this.CampaignName,
				CampaignDesc=this.CampaignDesc,
				Owner=this.Owner,
				ApprovalRequest=this.ApprovalRequest,
				Approved=this.Approved,
				ApprovedBy=this.ApprovedBy,
				ApprovedDate=this.ApprovedDate,
				Guid=this.Guid,
				Submitted=this.Submitted,
				CreatedDate=this.CreatedDate,
				CreatedBy=this.CreatedBy,
				UpdatedDate=this.UpdatedDate,
				UpdatedBy=this.UpdatedBy,
			};
		}
	}
}
