//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simon8029.EMPDemo.Model
{
	public partial class EM_EmailInstances
	{
		public EM_EmailInstances ToPOCO(){
			return new EM_EmailInstances(){
								EmailInstanceID=this.EmailInstanceID,
				CampaignID=this.CampaignID,
				SubjectLine=this.SubjectLine,
				EmailBody=this.EmailBody,
				Step=this.Step,
				PreviousStep=this.PreviousStep,
				EnableTracking=this.EnableTracking,
				IsDraft=this.IsDraft,
				Timespan=this.Timespan,
				AbsoluteDate=this.AbsoluteDate,
				CreatedDate=this.CreatedDate,
				CreatedBy=this.CreatedBy,
				UpdatedDate=this.UpdatedDate,
				UpdatedBy=this.UpdatedBy,
			};
		}
	}
}
