//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simon8029.EMPDemo.Model
{
	public partial class EM_EmailTemplateTypes
	{
		public EM_EmailTemplateTypes ToPOCO(){
			return new EM_EmailTemplateTypes(){
			EmailTemplateTypeID=this.EmailTemplateTypeID,
			EmailTemplateType=this.EmailTemplateType,
			};
		}
	}
}
