//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simon8029.EMPDemo.Model
{
	public partial class EM_Events
	{
		public EM_Events ToPOCO(){
			return new EM_Events(){
				EventID=this.EventID,
				EventName=this.EventName,
				EventDesc=this.EventDesc,
			};
		}
	}
}
