//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simon8029.EMPDemo.Model
{
	public partial class Employee
	{
		public Employee ToPOCO(){
			return new Employee(){
				employeeID=this.employeeID,
				employeeDepartmentID=this.employeeDepartmentID,
				employeeCnName=this.employeeCnName,
				employeeLoginName=this.employeeLoginName,
				employeeLoginPassword=this.employeeLoginPassword,
				employeeGender=this.employeeGender,
				employeePhone=this.employeePhone,
				employeeAddress=this.employeeAddress,
				employeeIsDeleted=this.employeeIsDeleted,
				employeeAddTime=this.employeeAddTime,
			};
		}
	}
}
