//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simon8029.EMPDemo.Model
{
	public partial class RolePermissionRelationship
	{
		public RolePermissionRelationship ToPOCO(){
			return new RolePermissionRelationship(){
				rolePermissionRelationID=this.rolePermissionRelationID,
				roleID=this.roleID,
				permissionID=this.permissionID,
			};
		}
	}
}
