//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simon8029.EMPDemo.Model
{
	public partial class VipPermission
	{
		public VipPermission ToPOCO(){
			return new VipPermission(){
				vipPermissionID=this.vipPermissionID,
				userID=this.userID,
				permissionID=this.permissionID,
			};
		}
	}
}
