
 //------------------------------------------------------------------------------
// <auto-generated>
// 数据仓储接口，作用：
// 1.调用EF容器 批量 执行 sql语句
// 2.方便通过 子接口属性直接 获取 对应数据表的操作接口对象
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simon8029.EMPDemo.IRepository
{
    using System;
    public partial interface IDbSession
    {
        IEM_CampaignInstancesRepository EM_CampaignInstancesRepository
    	{ 
    		get;
    	}
    
        IEM_CampaignsRepository EM_CampaignsRepository
    	{ 
    		get;
    	}
    
        IEM_EmailInstancesRepository EM_EmailInstancesRepository
    	{ 
    		get;
    	}
    
        IEM_EmailTemplatesRepository EM_EmailTemplatesRepository
    	{ 
    		get;
    	}
    
        IEM_EmailTemplateTypesRepository EM_EmailTemplateTypesRepository
    	{ 
    		get;
    	}
    
        IEM_EventsRepository EM_EventsRepository
    	{ 
    		get;
    	}
    
        IEM_LeadsRepository EM_LeadsRepository
    	{ 
    		get;
    	}
    
    }
}
