//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simon8029.EMPDemo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EM_CampaignInstances
    {
        public int CampaignInstanceID { get; set; }
        public Nullable<int> EmailInstanceID { get; set; }
        public Nullable<int> LeadID { get; set; }
        public Nullable<bool> IsSent { get; set; }
        public Nullable<int> EventID { get; set; }
        public string EventStatus { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public System.Guid Guid { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual EM_EmailInstances EM_EmailInstances { get; set; }
        public virtual EM_Events EM_Events { get; set; }
        public virtual EM_Leads EM_Leads { get; set; }
    }
}
