//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simon8029.EMPDemo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EM_EmailTemplates
    {
        public int EmailTemplateID { get; set; }
        public Nullable<short> EmailTemplateTypeID { get; set; }
        public Nullable<short> TemplateTypeID { get; set; }
        public string Template { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Updatedby { get; set; }
    
        public virtual EM_EmailTemplateTypes EM_EmailTemplateTypes { get; set; }
    }
}
