//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simon8029.EMPDemo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EM_Events
    {
        public EM_Events()
        {
            this.EM_CampaignInstances = new HashSet<EM_CampaignInstances>();
        }
    
        public int EventID { get; set; }
        public string EventName { get; set; }
        public string EventDesc { get; set; }
    
        public virtual ICollection<EM_CampaignInstances> EM_CampaignInstances { get; set; }
    }
}
