//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simon8029.EMPDemo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.employeeRoleRelationship = new HashSet<employeeRoleRelationship>();
            this.RolePermissionRelationship = new HashSet<RolePermissionRelationship>();
        } 
    
        public int roleID { get; set; }
        public Nullable<int> roleDepartmentID { get; set; }
        public string roleName { get; set; }
        public bool roleIsDeleted { get; set; }
        public System.DateTime roleAddTime { get; set; }
    
        public virtual ICollection<employeeRoleRelationship> employeeRoleRelationship { get; set; }
        public virtual ICollection<RolePermissionRelationship> RolePermissionRelationship { get; set; }
    }
}
