//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simon8029.EMPDemo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VipPermission
    {
        public int vipPermissionID { get; set; }
        public int userID { get; set; }
        public int permissionID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Permission Permission { get; set; }
    }
}
